name: car_price_prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - tensorflow=2.4
  - pip:
      - tensorflow-addons
      - plotly
      - keras
      - opencv-python